language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

env:
  # Ensure that we build without warnings.
  - CARGO_FLAGS="--features 'strict'"

script:
  # Configure Emacs for building
  - ./autogen.sh
  # TODO: set up makeinfo on travis.
  - ./configure --without-makeinfo --with-xpm=no --with-gif=no --with-gnutls=no
  - make -j 3

  - make check || echo 'make check failed'

notifications:
  fast_finish: true
  email: false

matrix:
  allow_failures:
    - rust: nightly
    - os: osx
  # Only build on stable for OS X, to keep our builds quick.
  exclude:
    - os: osx
      rust: nightly
    - os: osx
      rust: beta
